import Navbar from "./navbar";
import Footer from "./footer";
import { cookieToInitialState } from "wagmi";
import type { Metadata } from "next";
// import { headers } from "next/headers";
// import { cookies } from "next/headers";
import { config } from "@/config";
import Web3ModalProvider from "@/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  const initialState = cookieToInitialState(config, null);
  // const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-grow grid grid-cols-8 gap-x-4 pb-10">
        <div className="col-start-2 col-span-6 mt-5">
          <Web3ModalProvider initialState={initialState}>
            {children}
          </Web3ModalProvider>
        </div>
      </main>
      <Footer />
    </div>
  );
}
